### ISSUE TITLE
Add more info per verbosity level

### ISSUE THREAD

**Issue by nkakouros** [octplane/ansible_stdout_compact_logger#10]
It would be really helpful to add more info as greater verbosity level is given.

- vvv: could show the current yml file and line number
- vvvv: could show connection parameters

**Comment by octplane** [comment]
Hello,

I have just pushed the yaml file info starting a `vv`. The decision to put this at `vv` rather than `vvv` is because at `vvv`, it starts getting very chatty:

- starting at `vvv`, the SSH connector already dumps the connection information:

https://github.com/ansible/ansible/blob/e68f895e61de8ea7faa6ca22951dd9993a18f0d6/lib/ansible/plugins/connection/ssh.py#L1062

```
<1.1.1.1> ESTABLISH SSH CONNECTION FOR USER: root
<1.1.1.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/pierrebaillet/.ansible/cp/50d66f04bc 1.1.1.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1538426941.301826-70779379381518 `" && echo ansible-tmp-1538426941.301826-70779379381518="` echo /root/.ansible/tmp/ansible-tmp-1538426941.301826-70779379381518 `" ) && sleep 0'"'"''
<109.238.6.126> (0, b'ansible-tmp-1538426941.301826-70779379381518=/root/.ansible/tmp/ansible-tmp-1538426941.301826-70779379381518\n', b'')
```

**Comment by nkakouros** [comment]
Great, thanks a lot!
